stages:
- validate_plan
- apply_plan
- destroy

.template:
  image:
    name: hashicorp/terraform:1.5.7
    entrypoint: [""]
  before_script:
  - terraform init

validate & plan:
  extends: .template
  stage: validate_plan
  script:
  - terraform validate
  - terraform plan -out=plan.out
  cache:
    key: plan
    policy: push
    paths:
      - plan.out

apply plan:
  extends: .template
  stage: apply_plan
  script:
  - terraform apply plan.out
  cache:
    key: plan
    policy: pull
    path:
    - plan.out
  when: manual

destroy:
  extends: .template
  stage: destroy
  script:
  - terraform destroy -auto-approve
  when: manual